#!/usr/bin/env python3
"""
start_app.py — Basivo one-file launcher for cloud servers
----------------------------------------------------------
Usage:
    python3 start_app.py              # production (builds frontend, serves via uvicorn)
    python3 start_app.py --dev        # dev mode   (uvicorn --reload + vite dev server)
    python3 start_app.py --port 9000  # custom port
    python3 start_app.py --host 127.0.0.1

What this script does automatically:
    1. Checks Python / Node / npm versions
    2. Creates .env with secure random secrets if one does not exist
    3. Creates a Python venv (.venv/) and installs requirements.txt
    4. Ensures the PostgreSQL DB + user exist
    5. Runs Alembic migrations (alembic upgrade head)
    6. Installs npm dependencies and builds the React frontend
    7. Starts uvicorn (production) or uvicorn + vite (dev)
"""

from __future__ import annotations

import argparse
import os
import platform
import shutil
import signal
import subprocess
import sys
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────────────

ROOT = Path(__file__).parent.resolve()
VENV = ROOT / ".venv"
FRONTEND = ROOT / "frontend"
DIST = FRONTEND / "dist"
ENV_FILE = ROOT / ".env"
PROJECTS_DIR = ROOT / "projects"

# ── Colours ───────────────────────────────────────────────────────────────────

CYAN  = "\033[0;36m"
GREEN = "\033[0;32m"
YELLOW= "\033[1;33m"
RED   = "\033[0;31m"
BOLD  = "\033[1m"
RESET = "\033[0m"

def log(msg: str)  -> None: print(f"{CYAN}[basivo]{RESET} {msg}")
def ok(msg: str)   -> None: print(f"{GREEN}[basivo]{RESET} {msg}")
def warn(msg: str) -> None: print(f"{YELLOW}[basivo]{RESET} {msg}")
def die(msg: str)  -> None: print(f"{RED}[basivo] ERROR:{RESET} {msg}", file=sys.stderr); sys.exit(1)

# ── Helpers ───────────────────────────────────────────────────────────────────

def run(cmd: list[str], *, cwd: Path = ROOT, env: dict | None = None,
        capture: bool = False) -> subprocess.CompletedProcess:
    """Run a command, raising SystemExit on failure."""
    merged_env = {**os.environ, **(env or {})}
    result = subprocess.run(
        cmd, cwd=str(cwd), env=merged_env,
        capture_output=capture, text=True,
    )
    if result.returncode != 0:
        if capture:
            print(result.stderr or result.stdout, file=sys.stderr)
        die(f"Command failed: {' '.join(cmd)}")
    return result


def python_in_venv() -> str:
    """Return the path to the Python interpreter inside the venv."""
    if platform.system() == "Windows":
        return str(VENV / "Scripts" / "python.exe")
    return str(VENV / "bin" / "python")


def pip_in_venv() -> str:
    if platform.system() == "Windows":
        return str(VENV / "Scripts" / "pip.exe")
    return str(VENV / "bin" / "pip")


def alembic_in_venv() -> str:
    if platform.system() == "Windows":
        return str(VENV / "Scripts" / "alembic.exe")
    return str(VENV / "bin" / "alembic")


def uvicorn_in_venv() -> str:
    if platform.system() == "Windows":
        return str(VENV / "Scripts" / "uvicorn.exe")
    return str(VENV / "bin" / "uvicorn")

# ── Step 1 — Prerequisite checks ─────────────────────────────────────────────

def check_prerequisites() -> None:
    log("Checking prerequisites…")

    # Python version
    major, minor = sys.version_info.major, sys.version_info.minor
    if (major, minor) < (3, 11):
        die(f"Python 3.11+ required, found {major}.{minor}")
    log(f"Python {major}.{minor} ✓")

    # Node
    if not shutil.which("node"):
        die("Node.js not found. Install it: https://nodejs.org")
    node_ver = subprocess.check_output(["node", "--version"], text=True).strip()
    log(f"Node {node_ver} ✓")

    # npm
    if not shutil.which("npm"):
        die("npm not found. Install Node.js: https://nodejs.org")
    npm_ver = subprocess.check_output(["npm", "--version"], text=True).strip()
    log(f"npm {npm_ver} ✓")

    # opencode (warn only — app starts without it but AI features won't work)
    if not shutil.which("opencode"):
        warn("opencode binary not found in PATH — AI workspace features will not work.")
        warn("Install it: https://opencode.ai/docs/installation")

# ── Step 2 — Generate .env ────────────────────────────────────────────────────

def ensure_env() -> None:
    if ENV_FILE.exists():
        log(f"Using existing {ENV_FILE.name}")
        return

    warn(".env not found — generating one with secure random secrets…")

    import secrets as _secrets
    jwt_key = _secrets.token_hex(32)

    # Fernet key — requires cryptography; fall back to a raw urlsafe-b64 key
    try:
        from cryptography.fernet import Fernet
        fernet_key = Fernet.generate_key().decode()
    except ImportError:
        import base64
        fernet_key = base64.urlsafe_b64encode(os.urandom(32)).decode()

    db_url = "postgresql+asyncpg://basivo:basivo@localhost:5432/basivo"

    ENV_FILE.write_text(f"""\
# Auto-generated by start_app.py — review before sharing this file!
DEBUG=false
CORS_ORIGINS=["http://localhost:8000","http://localhost:3000"]

DATABASE_URL={db_url}

JWT_SECRET_KEY={jwt_key}
JWT_ALGORITHM=HS256
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=1440

ENCRYPTION_KEY={fernet_key}

RESET_TOKEN_EXPIRE_MINUTES=30

OPENCODE_BINARY=opencode
PROJECTS_ROOT={PROJECTS_DIR}
OPENCODE_TIMEOUT_SECONDS=300
""")
    ok(f".env created at {ENV_FILE}")
    warn("Review .env before going to production (set DEBUG=false, restrict CORS_ORIGINS).")

# ── Step 3 — Python venv + dependencies ──────────────────────────────────────

def ensure_venv() -> None:
    if not VENV.exists():
        log("Creating Python virtual environment (.venv)…")
        run([sys.executable, "-m", "venv", str(VENV)])
        ok("Virtual environment created")

    log("Installing Python dependencies…")
    run([pip_in_venv(), "install", "--quiet", "--upgrade", "pip"])
    run([pip_in_venv(), "install", "--quiet", "-r", "requirements.txt"])
    ok("Python dependencies installed")

# ── Step 4 — PostgreSQL DB + user ────────────────────────────────────────────

def ensure_postgres() -> None:
    log("Checking PostgreSQL…")

    pg_isready = shutil.which("pg_isready")
    if pg_isready:
        r = subprocess.run([pg_isready, "-q"], capture_output=True)
        if r.returncode != 0:
            warn("PostgreSQL not responding — trying to start it…")
            for cmd in (
                ["service", "postgresql", "start"],
                ["pg_ctlcluster", "16", "main", "start"],
                ["pg_ctlcluster", "15", "main", "start"],
                ["pg_ctl", "start", "-D", "/var/lib/postgresql/data"],
            ):
                if shutil.which(cmd[0]):
                    subprocess.run(cmd, capture_output=True)
                    break
            import time; time.sleep(2)

            r = subprocess.run([pg_isready, "-q"], capture_output=True)
            if r.returncode != 0:
                die("PostgreSQL is not running. Start it with: service postgresql start")

    ok("PostgreSQL is running")

    # Create role + DB if missing (no-op if they already exist)
    _psql_exec("CREATE USER basivo WITH PASSWORD 'basivo';",  ignore_errors=True)
    _psql_exec("CREATE DATABASE basivo OWNER basivo;",        ignore_errors=True)
    ok("Database 'basivo' ready")


def _psql_exec(sql: str, ignore_errors: bool = False) -> None:
    """Run a SQL statement as the postgres superuser."""
    for psql_cmd in (
        ["sudo", "-u", "postgres", "psql", "-c", sql],
        ["psql", "-U", "postgres",          "-c", sql],
    ):
        if shutil.which(psql_cmd[0]):
            r = subprocess.run(psql_cmd, capture_output=True, text=True)
            if r.returncode == 0 or ignore_errors:
                return
    if not ignore_errors:
        warn("Could not run psql — make sure PostgreSQL is accessible.")

# ── Step 5 — Alembic migrations ───────────────────────────────────────────────

def run_migrations() -> None:
    log("Running database migrations…")
    run(
        [alembic_in_venv(), "upgrade", "head"],
        env={"PYTHONPATH": str(ROOT)},
    )
    ok("Migrations applied")

# ── Step 6 — Frontend ─────────────────────────────────────────────────────────

def ensure_frontend(dev_mode: bool) -> None:
    log("Setting up frontend…")

    if not (FRONTEND / "node_modules").exists():
        log("Installing npm dependencies (first run may take a minute)…")
        run(["npm", "install", "--prefer-offline"], cwd=FRONTEND)
        ok("npm dependencies installed")

    if not dev_mode:
        log("Building React frontend for production…")
        run(["npm", "run", "build"], cwd=FRONTEND)
        ok(f"Frontend built → {DIST}")

# ── Step 7 — Start servers ────────────────────────────────────────────────────

def start_production(host: str, port: int) -> None:
    if not DIST.exists():
        die(f"{DIST} not found. Run without --dev to build the frontend first.")

    PROJECTS_DIR.mkdir(parents=True, exist_ok=True)

    print(f"\n{BOLD}{GREEN}  ✓ Basivo is running{RESET}")
    print(f"  App:    {CYAN}http://{host}:{port}{RESET}")
    print(f"  API:    {CYAN}http://{host}:{port}/api/docs{RESET}")
    print(f"  Health: {CYAN}http://{host}:{port}/health{RESET}")
    print(f"\n  Press Ctrl+C to stop\n")

    os.execv(uvicorn_in_venv(), [
        uvicorn_in_venv(),
        "app.main:app",
        "--host", host,
        "--port", str(port),
        "--workers", "1",
        "--log-level", "info",
    ])


def start_dev(host: str, port: int) -> None:
    PROJECTS_DIR.mkdir(parents=True, exist_ok=True)

    print(f"\n{BOLD}{GREEN}  ✓ Basivo — dev mode{RESET}")
    print(f"  Backend: {CYAN}http://{host}:{port}/api/docs{RESET}")
    print(f"  Frontend:{CYAN}http://localhost:5173{RESET}")
    print(f"\n  Press Ctrl+C to stop\n")

    backend = subprocess.Popen([
        uvicorn_in_venv(), "app.main:app",
        "--host", host, "--port", str(port),
        "--reload", "--log-level", "info",
    ], cwd=str(ROOT))

    vite = subprocess.Popen(["npm", "run", "dev"], cwd=str(FRONTEND))

    def _stop(sig, frame):
        log("Stopping…")
        backend.terminate()
        vite.terminate()
        sys.exit(0)

    signal.signal(signal.SIGINT,  _stop)
    signal.signal(signal.SIGTERM, _stop)

    backend.wait()
    vite.wait()

# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Basivo launcher")
    parser.add_argument("--dev",  action="store_true", help="Run in development mode (hot-reload)")
    parser.add_argument("--host", default="127.0.0.1", help="Bind host (default: 127.0.0.1 — expose via nginx)")
    parser.add_argument("--port", type=int, default=8000, help="Bind port (default: 8000)")
    args = parser.parse_args()

    print(f"\n{BOLD}  Basivo — AI Coding Platform{RESET}")
    print(f"  {'development' if args.dev else 'production'} mode\n")

    check_prerequisites()
    ensure_env()
    ensure_venv()
    ensure_postgres()
    run_migrations()
    ensure_frontend(dev_mode=args.dev)

    if args.dev:
        start_dev(args.host, args.port)
    else:
        start_production(args.host, args.port)


if __name__ == "__main__":
    main()
